# Generated by Django 6.0.5 on 2026-05-30 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Текст статті')),
                ('publication_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публікації')),
            ],
        ),
    ]
